version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.11.0
    - 3.9.1
  - dependency-name: sass
    versions:
    - 1.32.11
    - 1.32.8
  - dependency-name: eslint
    versions:
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@types/marked"
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.7.0
    - 7.8.0
  - dependency-name: typescript
    versions:
    - 4.2.3
